root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server-go-air.exe ."
bin = "./tmp/server-go-air.exe"
delay = 1000
exclude_dir = ["tmp", "uploads", "data"]
include_ext = ["go"]
kill_delay = "1s"
send_interrupt = true
stop_on_error = true

[log]
time = true

[misc]
clean_on_exit = true
